//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HLSLPreprocessorParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace March.ShaderLab.Internal {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class HLSLPreprocessorParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		Sharp=1, BlockComment=2, LineComment=3, Code=4, Include=5, Pragma=6, DirectiveWhitespace=7, 
		DirectiveBlockComment=8, DirectiveLineComment=9, DirectiveNewline=10, 
		Newline=11, DirectiveTextNewline=12, DirectiveTextBlockComment=13, DirectiveTextLineComment=14, 
		Text=15, Slash=16;
	public const int
		RULE_program = 0, RULE_text = 1, RULE_directive = 2, RULE_directiveText = 3;
	public static readonly string[] ruleNames = {
		"program", "text", "directive", "directiveText"
	};

	private static readonly string[] _LiteralNames = {
		null, "'#'", null, null, null, "'include'", "'pragma'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "Sharp", "BlockComment", "LineComment", "Code", "Include", "Pragma", 
		"DirectiveWhitespace", "DirectiveBlockComment", "DirectiveLineComment", 
		"DirectiveNewline", "Newline", "DirectiveTextNewline", "DirectiveTextBlockComment", 
		"DirectiveTextLineComment", "Text", "Slash"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "HLSLPreprocessorParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static HLSLPreprocessorParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public HLSLPreprocessorParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public HLSLPreprocessorParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(HLSLPreprocessorParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TextContext[] text() {
			return GetRuleContexts<TextContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text(int i) {
			return GetRuleContext<TextContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHLSLPreprocessorParserVisitor<TResult> typedVisitor = visitor as IHLSLPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 11;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==Sharp || _la==Code) {
				{
				{
				State = 8;
				text();
				}
				}
				State = 13;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 14;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Sharp() { return GetToken(HLSLPreprocessorParser.Sharp, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Newline() { return GetToken(HLSLPreprocessorParser.Newline, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveContext directive() {
			return GetRuleContext<DirectiveContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(HLSLPreprocessorParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Code() { return GetTokens(HLSLPreprocessorParser.Code); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Code(int i) {
			return GetToken(HLSLPreprocessorParser.Code, i);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHLSLPreprocessorParserVisitor<TResult> typedVisitor = visitor as IHLSLPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 2, RULE_text);
		int _la;
		try {
			int _alt;
			State = 37;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 16;
				Match(Sharp);
				State = 18;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Include || _la==Pragma) {
					{
					State = 17;
					directive();
					}
				}

				State = 20;
				Match(Newline);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 21;
				Match(Sharp);
				State = 23;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Include || _la==Pragma) {
					{
					State = 22;
					directive();
					}
				}

				State = 25;
				Match(Eof);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 26;
				Match(Sharp);
				State = 28;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 27;
						Match(Code);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 30;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 33;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 32;
						Match(Code);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 35;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveContext : ParserRuleContext {
		public DirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive; } }
	 
		public DirectiveContext() { }
		public virtual void CopyFrom(DirectiveContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class PreprocessorPragmaContext : DirectiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pragma() { return GetToken(HLSLPreprocessorParser.Pragma, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveTextContext directiveText() {
			return GetRuleContext<DirectiveTextContext>(0);
		}
		public PreprocessorPragmaContext(DirectiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHLSLPreprocessorParserVisitor<TResult> typedVisitor = visitor as IHLSLPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorPragma(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PreprocessorIncludeContext : DirectiveContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Include() { return GetToken(HLSLPreprocessorParser.Include, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveTextContext directiveText() {
			return GetRuleContext<DirectiveTextContext>(0);
		}
		public PreprocessorIncludeContext(DirectiveContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHLSLPreprocessorParserVisitor<TResult> typedVisitor = visitor as IHLSLPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessorInclude(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DirectiveContext directive() {
		DirectiveContext _localctx = new DirectiveContext(Context, State);
		EnterRule(_localctx, 4, RULE_directive);
		int _la;
		try {
			State = 47;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Include:
				_localctx = new PreprocessorIncludeContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 39;
				Match(Include);
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Text) {
					{
					State = 40;
					directiveText();
					}
				}

				}
				break;
			case Pragma:
				_localctx = new PreprocessorPragmaContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 43;
				Match(Pragma);
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Text) {
					{
					State = 44;
					directiveText();
					}
				}

				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveTextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Text() { return GetTokens(HLSLPreprocessorParser.Text); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Text(int i) {
			return GetToken(HLSLPreprocessorParser.Text, i);
		}
		public DirectiveTextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directiveText; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHLSLPreprocessorParserVisitor<TResult> typedVisitor = visitor as IHLSLPreprocessorParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDirectiveText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DirectiveTextContext directiveText() {
		DirectiveTextContext _localctx = new DirectiveTextContext(Context, State);
		EnterRule(_localctx, 6, RULE_directiveText);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 49;
				Match(Text);
				}
				}
				State = 52;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Text );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,16,55,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,5,0,10,8,0,10,0,12,0,13,
		9,0,1,0,1,0,1,1,1,1,3,1,19,8,1,1,1,1,1,1,1,3,1,24,8,1,1,1,1,1,1,1,4,1,
		29,8,1,11,1,12,1,30,1,1,4,1,34,8,1,11,1,12,1,35,3,1,38,8,1,1,2,1,2,3,2,
		42,8,2,1,2,1,2,3,2,46,8,2,3,2,48,8,2,1,3,4,3,51,8,3,11,3,12,3,52,1,3,0,
		0,4,0,2,4,6,0,0,62,0,11,1,0,0,0,2,37,1,0,0,0,4,47,1,0,0,0,6,50,1,0,0,0,
		8,10,3,2,1,0,9,8,1,0,0,0,10,13,1,0,0,0,11,9,1,0,0,0,11,12,1,0,0,0,12,14,
		1,0,0,0,13,11,1,0,0,0,14,15,5,0,0,1,15,1,1,0,0,0,16,18,5,1,0,0,17,19,3,
		4,2,0,18,17,1,0,0,0,18,19,1,0,0,0,19,20,1,0,0,0,20,38,5,11,0,0,21,23,5,
		1,0,0,22,24,3,4,2,0,23,22,1,0,0,0,23,24,1,0,0,0,24,25,1,0,0,0,25,38,5,
		0,0,1,26,28,5,1,0,0,27,29,5,4,0,0,28,27,1,0,0,0,29,30,1,0,0,0,30,28,1,
		0,0,0,30,31,1,0,0,0,31,38,1,0,0,0,32,34,5,4,0,0,33,32,1,0,0,0,34,35,1,
		0,0,0,35,33,1,0,0,0,35,36,1,0,0,0,36,38,1,0,0,0,37,16,1,0,0,0,37,21,1,
		0,0,0,37,26,1,0,0,0,37,33,1,0,0,0,38,3,1,0,0,0,39,41,5,5,0,0,40,42,3,6,
		3,0,41,40,1,0,0,0,41,42,1,0,0,0,42,48,1,0,0,0,43,45,5,6,0,0,44,46,3,6,
		3,0,45,44,1,0,0,0,45,46,1,0,0,0,46,48,1,0,0,0,47,39,1,0,0,0,47,43,1,0,
		0,0,48,5,1,0,0,0,49,51,5,15,0,0,50,49,1,0,0,0,51,52,1,0,0,0,52,50,1,0,
		0,0,52,53,1,0,0,0,53,7,1,0,0,0,10,11,18,23,30,35,37,41,45,47,52
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace March.ShaderLab.Internal
