#ifndef _SAMPLER_INCLUDED
#define _SAMPLER_INCLUDED

// Static Samplers
// https://docs.unity3d.com/Manual/SL-SamplerStates.html

SamplerState sampler_PointRepeat;
SamplerState sampler_LinearRepeat;
SamplerState sampler_TrilinearRepeat;
SamplerState sampler_Aniso1Repeat;
SamplerState sampler_Aniso2Repeat;
SamplerState sampler_Aniso3Repeat;
SamplerState sampler_Aniso4Repeat;
SamplerState sampler_Aniso5Repeat;
SamplerState sampler_Aniso6Repeat;
SamplerState sampler_Aniso7Repeat;
SamplerState sampler_Aniso8Repeat;
SamplerState sampler_Aniso9Repeat;
SamplerState sampler_Aniso10Repeat;
SamplerState sampler_Aniso11Repeat;
SamplerState sampler_Aniso12Repeat;
SamplerState sampler_Aniso13Repeat;
SamplerState sampler_Aniso14Repeat;
SamplerState sampler_Aniso15Repeat;
SamplerState sampler_Aniso16Repeat;

SamplerState sampler_PointClamp;
SamplerState sampler_LinearClamp;
SamplerState sampler_TrilinearClamp;
SamplerState sampler_Aniso1Clamp;
SamplerState sampler_Aniso2Clamp;
SamplerState sampler_Aniso3Clamp;
SamplerState sampler_Aniso4Clamp;
SamplerState sampler_Aniso5Clamp;
SamplerState sampler_Aniso6Clamp;
SamplerState sampler_Aniso7Clamp;
SamplerState sampler_Aniso8Clamp;
SamplerState sampler_Aniso9Clamp;
SamplerState sampler_Aniso10Clamp;
SamplerState sampler_Aniso11Clamp;
SamplerState sampler_Aniso12Clamp;
SamplerState sampler_Aniso13Clamp;
SamplerState sampler_Aniso14Clamp;
SamplerState sampler_Aniso15Clamp;
SamplerState sampler_Aniso16Clamp;

SamplerState sampler_PointMirror;
SamplerState sampler_LinearMirror;
SamplerState sampler_TrilinearMirror;
SamplerState sampler_Aniso1Mirror;
SamplerState sampler_Aniso2Mirror;
SamplerState sampler_Aniso3Mirror;
SamplerState sampler_Aniso4Mirror;
SamplerState sampler_Aniso5Mirror;
SamplerState sampler_Aniso6Mirror;
SamplerState sampler_Aniso7Mirror;
SamplerState sampler_Aniso8Mirror;
SamplerState sampler_Aniso9Mirror;
SamplerState sampler_Aniso10Mirror;
SamplerState sampler_Aniso11Mirror;
SamplerState sampler_Aniso12Mirror;
SamplerState sampler_Aniso13Mirror;
SamplerState sampler_Aniso14Mirror;
SamplerState sampler_Aniso15Mirror;
SamplerState sampler_Aniso16Mirror;

SamplerState sampler_PointMirrorOnce;
SamplerState sampler_LinearMirrorOnce;
SamplerState sampler_TrilinearMirrorOnce;
SamplerState sampler_Aniso1MirrorOnce;
SamplerState sampler_Aniso2MirrorOnce;
SamplerState sampler_Aniso3MirrorOnce;
SamplerState sampler_Aniso4MirrorOnce;
SamplerState sampler_Aniso5MirrorOnce;
SamplerState sampler_Aniso6MirrorOnce;
SamplerState sampler_Aniso7MirrorOnce;
SamplerState sampler_Aniso8MirrorOnce;
SamplerState sampler_Aniso9MirrorOnce;
SamplerState sampler_Aniso10MirrorOnce;
SamplerState sampler_Aniso11MirrorOnce;
SamplerState sampler_Aniso12MirrorOnce;
SamplerState sampler_Aniso13MirrorOnce;
SamplerState sampler_Aniso14MirrorOnce;
SamplerState sampler_Aniso15MirrorOnce;
SamplerState sampler_Aniso16MirrorOnce;

#endif
